// Curated Miami-Dade County middle & high school list for the "School currently
// attending" combobox on the Open House Registration form. Not exhaustive by
// design — a searchable list of well-known schools, with free typing as the
// fallback for anything missing. `isADOM` drives whether the PowerSchool #
// field appears (Archdiocese of Miami schools share a PowerSchool instance).
//
// Compiled 2026-08-31 from the Archdiocese of Miami's official school
// directory (cross-checked school-by-school against each school's live
// website) for the isADOM==true entries, and from Miami-Dade County Public
// Schools / charter-network sites / individual private-school sites for the
// rest. Not a full county enumeration (227 of ~300+ schools) — see chat for
// the full sourcing and gaps notes. Recommend a spot-check of spellings
// against dadeschools.net's school locator before this goes live.
const SCHOOLS = [
  { name: "Academir Charter School Middle", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "AcadeMir Preparatory High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Academy for Advanced Academics", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "All Saints Catholic School", city: "Sunrise", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "Allapattah Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Alonzo and Tracy Mourning Senior High Biscayne Bay Campus", city: "North Miami Beach", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Alpha School Miami", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "American Senior High School", city: "Hialeah", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Andover Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Annunciation Catholic School", city: "West Park", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "Archbishop Coleman F. Carroll High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "Archbishop Edward A. McCarthy High School", city: "Southwest Ranches", county: "Broward", level: "high", isADOM: true, type: "private" },
  { name: "Archimedean Middle Conservatory", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Archimedean Upper Conservatory", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Arthur and Polly Mays Conservatory of the Arts", city: "Goulds", county: "Miami-Dade", level: "both", isADOM: false, type: "public" },
  { name: "Arvida Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Aventura City of Excellence School", city: "Aventura", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Barbara Goleman Senior High School", city: "Miami Lakes", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Basilica School of St. Mary Star of the Sea", city: "Key West", county: "Monroe", level: "middle", isADOM: true, type: "private" },
  { name: "Belen Jesuit Preparatory School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: true, type: "private" },
  { name: "Ben Gamla Charter School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Blessed Trinity Catholic School", city: "Miami Springs", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Booker T. Washington Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "BridgePrep Academy Interamerican Campus", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "BridgePrep Academy of Miami-Dade", city: "Doral", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Brownsville Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Cardinal Gibbons High School", city: "Fort Lauderdale", county: "Broward", level: "high", isADOM: true, type: "private" },
  { name: "Carol City Middle School", city: "Miami Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Carrollton School of the Sacred Heart", city: "Miami", county: "Miami-Dade", level: "both", isADOM: true, type: "private" },
  { name: "Centner Academy", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Chaminade-Madonna College Preparatory", city: "Hollywood", county: "Broward", level: "high", isADOM: true, type: "private" },
  { name: "Christ Fellowship Academy", city: "Palmetto Bay", county: "Miami-Dade", level: "middle", isADOM: false, type: "private" },
  { name: "Christopher Columbus High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "Citrus Grove Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Conchita Espinosa Academy", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "private" },
  { name: "Coral Gables Senior High School", city: "Coral Gables", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Coral Reef Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Cutler Bay Middle School", city: "Cutler Bay", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Cutler Bay Senior High School", city: "Cutler Bay", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Dade Christian School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Design and Architecture Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Divine Savior Academy", city: "Doral", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Doral Academy Charter High School", city: "Doral", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Doral Academy Charter Middle School", city: "Doral", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Doral Academy of Technology", city: "Doral", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Doral Performing Arts and Entertainment Academy", city: "Doral", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Downtown Doral Charter Upper School", city: "Doral", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Dr. Michael M. Krop Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Ebenezer Christian School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Epiphany Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Felix Varela Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Florida Christian School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Fusion Academy Miami", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "G. Holmes Braddock Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "George Washington Carver Middle School", city: "Coral Gables", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Glades Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Good Shepherd Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Grace Christian Preparatory", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Greater Miami Adventist Academy", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Gulliver Preparatory School", city: "Pinecrest", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Hammocks Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Hebrew Academy (RASG)", city: "Miami Beach", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Henry H. Filer Middle School", city: "Hialeah", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Herbert A. Ammons Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Hialeah Gardens High School", city: "Hialeah Gardens", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Hialeah Gardens Middle School", city: "Hialeah Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Hialeah Middle School", city: "Hialeah", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Hialeah Senior High School", city: "Hialeah", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Hialeah-Miami Lakes Senior High School", city: "Hialeah", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Highland Oaks Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Holy Family Catholic School", city: "North Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Homestead High School", city: "Homestead", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Homestead Middle School", city: "Homestead", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Horace Mann Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Howard D. McMillan Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "iMater Academy Middle High School", city: "Hialeah", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Immaculata-La Salle High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "Immaculate Conception School", city: "Hialeah", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "International Studies Charter Middle/High School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "iPreparatory Academy", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "public" },
  { name: "J.C. Bermudez Doral Senior High School", city: "Doral", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "John A. Ferguson Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "John F. Kennedy Middle School", city: "North Miami Beach", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Jorge Mas Canosa Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Jose de Diego Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Jose Marti MAST 6-12 Academy", city: "Hialeah", county: "Miami-Dade", level: "both", isADOM: false, type: "public" },
  { name: "JUST Arts and Management Charter Middle School", city: "Doral", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Key Point Academy", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "private" },
  { name: "Kinloch Park Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "KIPP Courage Academy", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "KIPP Legacy Middle", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "KIPP Miami Technical High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Lake Stevens Middle School", city: "Miami Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Lamar Louise Curry Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Lawton Chiles Middle School", city: "Miami Lakes", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Little Flower Catholic School", city: "Hollywood", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "Madison Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Marian Center School and Services", city: "Miami Gardens", county: "Miami-Dade", level: "both", isADOM: true, type: "private" },
  { name: "Mary Help of Christians Catholic School", city: "Parkland", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "MAST Academy", city: "Key Biscayne", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Mater Academy Bay", city: "Cutler Bay", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Mater Academy Biscayne", city: "North Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Mater Academy Charter High School", city: "Hialeah Gardens", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Mater Academy Charter Middle School", city: "Hialeah Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Mater Academy East Charter School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Mater Academy of International Studies", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Mater Brickell Preparatory Academy", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Mater Grove Academy", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Mater Lakes Academy", city: "Hialeah", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Mater Performing Arts and Entertainment Academy", city: "Hialeah Gardens", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Miami Arts Studio at Zelda Glazer 6-12", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "public" },
  { name: "Miami Beach Senior High School", city: "Miami Beach", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Carol City Senior High School", city: "Miami Gardens", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Central Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Christian School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Miami Community Charter High School", city: "Florida City", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Miami Community Charter Middle School", city: "Florida City", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Miami Coral Park Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Country Day School", city: "Miami Shores", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Miami Edison Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Miami Edison Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Jackson Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Killian Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Lakes Middle School", city: "Miami Lakes", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Miami Norland Senior High School", city: "Miami Gardens", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Northwestern Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Palmetto Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Southridge Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Springs Middle School", city: "Miami Springs", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Miami Springs Senior High School", city: "Miami Springs", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Sunset Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Miami Tech at Mater Innovation Academy", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Monsignor Edward Pace High School", city: "Miami Gardens", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "Mother of Christ Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Mother of Our Redeemer Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Nativity Catholic School", city: "Hollywood", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "Nautilus Middle School", city: "Miami Beach", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "New World School of the Arts", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Norland Middle School", city: "Miami Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "North Dade Middle School", city: "Miami Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "North Miami Beach Senior High School", city: "North Miami Beach", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "North Miami Middle School", city: "North Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "North Miami Senior High School", city: "North Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Our Lady of Lourdes Academy", city: "Miami", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "Our Lady of Lourdes Parish School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Our Lady of the Holy Rosary-St. Richard Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Our Lady of the Lakes Catholic School", city: "Miami Lakes", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Our Lady Queen of Martyrs School", city: "Fort Lauderdale", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "Palm Springs Middle School", city: "Hialeah", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Palmer Trinity School", city: "Palmetto Bay", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Palmetto Bay Academy", city: "Palmetto Bay", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Palmetto Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Paul W. Bell Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Pinecrest North Preparatory Fontainebleau Campus", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Pinecrest North Preparatory High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Pinecrest Preparatory Academy Charter High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Pinecrest Preparatory Middle High School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Ponce de Leon Middle School", city: "Coral Gables", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Ransom Everglades School", city: "Coconut Grove", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Redland Middle School", city: "Homestead", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Renaissance Charter School at Doral", city: "Doral", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "Richmond Heights Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Riviera Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Riviera Schools", city: "Coral Gables", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Robert Morgan Educational Center", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Rockway Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Ronald W. Reagan/Doral High School", city: "Doral", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Ruben Dario Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Scheck Hillel Community School", city: "Aventura", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "School for Advanced Studies", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Score Academy", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Shenandoah Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Somerset Academy Charter High School", city: "Homestead", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "Somerset Academy Charter Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Somerset Academy Charter Middle School South Miami Campus", city: "South Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Somerset Academy Preparatory", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Somerset Academy Silver Palms", city: "Homestead", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Somerset Academy Silver Palms at Princeton", city: "Homestead", county: "Miami-Dade", level: "middle", isADOM: false, type: "charter" },
  { name: "Somerset College Preparatory Academy South", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "charter" },
  { name: "South Dade Middle School", city: "Homestead", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "South Dade Senior High School", city: "Homestead", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "South Miami Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "South Miami Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Southwest Miami Senior High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Southwood Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Sports Leadership and Management Charter Middle/High School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "charter" },
  { name: "St. Agatha Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Agnes Catholic Academy", city: "Key Biscayne", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Ambrose Catholic School", city: "Deerfield Beach", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Andrew Catholic School", city: "Coral Springs", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Anthony School", city: "Fort Lauderdale", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Bartholomew Catholic School", city: "Miramar", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Bernadette Catholic School", city: "Hollywood", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Bonaventure Catholic School", city: "Davie", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Brendan Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Brendan High School", city: "Miami", county: "Miami-Dade", level: "high", isADOM: true, type: "private" },
  { name: "St. Coleman School", city: "Pompano Beach", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. David Catholic School", city: "Davie", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Gregory the Great School", city: "Plantation", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Helen Catholic School", city: "Fort Lauderdale", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Hugh Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. James Catholic School", city: "North Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Jerome Catholic School", city: "Fort Lauderdale", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. John Neumann Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. John the Apostle Catholic School", city: "Hialeah", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Kevin Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Lawrence Catholic School", city: "North Miami Beach", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Louis Covenant School", city: "Pinecrest", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Mark Catholic School", city: "Southwest Ranches", county: "Broward", level: "middle", isADOM: true, type: "private" },
  { name: "St. Mary Cathedral School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Michael the Archangel School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Patrick Catholic School", city: "Miami Beach", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Rose of Lima School", city: "Miami Shores", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Theresa School", city: "Coral Gables", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Thomas Aquinas High School", city: "Fort Lauderdale", county: "Broward", level: "high", isADOM: true, type: "private" },
  { name: "St. Thomas the Apostle Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "St. Timothy Catholic School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "Sts. Peter and Paul School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: true, type: "private" },
  { name: "TERRA Environmental Research Institute", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "The Cushman School", city: "Miami", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "W.R. Thomas Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "West Miami Middle School", city: "Miami", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Westland Hialeah Senior High School", city: "Hialeah", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
  { name: "Westminster Christian School", city: "Palmetto Bay", county: "Miami-Dade", level: "both", isADOM: false, type: "private" },
  { name: "Westview Middle School", city: "Miami Gardens", county: "Miami-Dade", level: "middle", isADOM: false, type: "public" },
  { name: "Young Men's Preparatory Academy", city: "Miami", county: "Miami-Dade", level: "high", isADOM: false, type: "public" },
];
